"""init

Revision ID: 2e8223a44c36
Revises: None
Create Date: 2015-12-23 04:27:28.864523

"""

# revision identifiers, used by Alembic.
revision = '2e8223a44c36'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
