"""init

Revision ID: 57cdca2df203
Revises: None
Create Date: 2015-12-18 12:08:49.170701

"""

# revision identifiers, used by Alembic.
revision = '57cdca2df203'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
