"""init

Revision ID: 2b2a95e82738
Revises: None
Create Date: 2015-12-18 12:55:41.694048

"""

# revision identifiers, used by Alembic.
revision = '2b2a95e82738'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
